# https://lambdaurora.dev/tools/import_quilt.html
[versions]
minecraft = "1.19.2"
quilt_mappings = "1.19.2+build.6"
# quilt_mappings = "1.19.2+build.intermediary-test.1"

quilt_loader = "0.17.3"
quilted_fabric_api = "4.0.0-beta.7+0.59.0-1.19.2"

narrator_off = "0.0.1"
no_auth = "0.0.1"
mod_menu = "4.0.6"
sodium = "mc1.19-0.4.2"
joml = "1.10.4"
lithium = "mc1.19.2-0.8.3"
lazydfu = "0.1.3"
starlight = "1.1.1+1.19"
ferrite_core = "5.0.0-fabric"
ebe = "0.7.1+1.19"
arrp = "0.6.4"
dynamic_fps = "2.2.0"
toml4j = "0.7.2"
memory_leak_fix = "v0.7.0"
forget_me_chunk = "1.0.4"

[libraries]
minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }
quilt_mappings = { module = "org.quiltmc:quilt-mappings", version.ref = "quilt_mappings" }

quilt_loader = { module = "org.quiltmc:quilt-loader", version.ref = "quilt_loader" }
quilted_fabric_api = { module = "org.quiltmc.quilted-fabric-api:quilted-fabric-api", version.ref = "quilted_fabric_api" }

narrator_off = { module = "net.auoeke:narrator-off", version.ref = "narrator_off" }
no_auth = { module = "net.auoeke:noauth", version.ref = "no_auth" }
sodium = { module = "maven.modrinth:sodium", version.ref = "sodium" }
joml = { module = "org.joml:joml", version.ref = "joml" }
lithium = { module = "maven.modrinth:lithium", version.ref = "lithium" }
lazydfu = { module = "maven.modrinth:lazydfu", version.ref = "lazydfu" }
starlight = { module = "maven.modrinth:starlight", version.ref = "starlight" }
ferrite_core = { module = "maven.modrinth:ferrite-core", version.ref = "ferrite_core" }
ebe = { module = "maven.modrinth:ebe", version.ref = "ebe" }
arrp = { module = "maven.modrinth:arrp", version.ref = "arrp" }
dynamic_fps = { module = "maven.modrinth:dynamic-fps", version.ref = "dynamic_fps" }
toml4j = { module = "com.moandjiezana.toml:toml4j", version.ref = "toml4j" }
memory_leak_fix = { module = "maven.modrinth:memoryleakfix", version.ref = "memory_leak_fix" }
forget_me_chunk = { module = "maven.modrinth:forgetmechunk", version.ref = "forget_me_chunk" }
mod_menu = { module = "com.terraformersmc:modmenu", version.ref = "mod_menu" }

[bundles]
quilt = ["quilt_loader", "quilted_fabric_api"]
runtime = [
	"narrator_off", "no_auth", "sodium", "joml", "lithium", "lazydfu", "starlight", "ferrite_core",
	"ebe", "arrp", "dynamic_fps", "toml4j", "memory_leak_fix", "forget_me_chunk", "mod_menu"
]

[plugins]
quilt_loom = { id = "org.quiltmc.loom", version = "0.12.+" }
