name: Build
on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-20.04
    container:
      image: adoptopenjdk:16-jdk
      options: --user root
    steps:
      - uses: actions/checkout@v2
      - uses: gradle/wrapper-validation-action@v1
      - uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: 16
      - run: ./gradlew build
